version: v0.10.1
formatter: default
rules:
  - header-min-length
  - header-max-length
  - body-max-line-length
  - type-enum
severity:
  default: error
settings:
  body-max-length:
    argument: -1
  body-max-line-length:
    argument: 72
  body-min-length:
    argument: 0
  description-max-length:
    argument: -1
  description-min-length:
    argument: 0
  header-max-length:
    argument: -1
  header-min-length:
    argument: 10
  scope-charset:
    argument: abcdefghijklmnopqrstuvwxyz-/,
  scope-enum:
    argument: []
    flags:
      allow-empty: true
  scope-max-length:
    argument: -1
  scope-min-length:
    argument: 0
  type-charset:
    argument: abcdefghijklmnopqrstuvwxyz
  type-enum:
    argument:
      - feat
      - fix
      - docs
      - refactor
      - chore
  type-max-length:
    argument: -1
  type-min-length:
    argument: 0
