version: "2"

run:
  go: "1.24.8"
  timeout: 5m

linters:
  settings:
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 15
    unparam:
      check-exported: true
    revive:
      rules:
        - name: var-naming
          disabled: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - forcetypeassert
    - gosec
    - misspell
    - testpackage
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
