name = "commitlint"
type = "cli"

[platform.linux]
download-file = "commitlint_v{version}_linux_{arch}.tar.gz"
checksum-file = "commitlint_v{version}_checksums.txt"
bin-path = "commitlint"

[platform.macos]
download-file = "commitlint_v{version}_darwin_{arch}.tar.gz"
checksum-file = "commitlint_v{version}_checksums.txt"
bin-path = "commitlint"

[platform.windows]
download-file = "commitlint_v{version}_windows_{arch}.tar.gz"
checksum-file = "commitlint_v{version}_checksums.txt"
bin-path = "commitlint.exe"

[install]
download-url = "https://github.com/conventionalcommit/commitlint/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/conventionalcommit/commitlint/releases/download/v{version}/{checksum_file}"
unpack = true

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
x86 = "386"

[resolve]
manifest-url = "https://api.github.com/repos/conventionalcommit/commitlint/releases?per_page=100"
manifest-version-key = "tag_name"
version-pattern = "^v?(\\d+\\.\\d+\\.\\d+)$"
