name = "hadolint"
type = "cli"

[metadata]
self-upgrade-commands = ["upgrade"]

[platform.linux]
download-file = "hadolint-linux-{arch}"
checksum-file = "hadolint-linux-{arch}.sha256"
bin-path = "hadolint"

[platform.macos]
download-file = "hadolint-macos-{arch}"
checksum-file = "hadolint-macos-{arch}.sha256"
bin-path = "hadolint"

[platform.windows]
download-file = "hadolint-windows-{arch}.exe"
checksum-file = "hadolint-windows-{arch}.exe.sha256"
bin-path = "hadolint.exe"

[install]
download-url = "https://github.com/hadolint/hadolint/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/hadolint/hadolint/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"

[resolve]
git-url = "https://github.com/hadolint/hadolint"
