name = "helm"
type = "cli"

[platform.linux]
download-file = "helm-v{version}-linux-{arch}.tar.gz"
checksum-file = "helm-v{version}-linux-{arch}.tar.gz.sha256sum"
archive-prefix = "linux-{arch}"
bin-path = "helm"

[platform.macos]
download-file = "helm-v{version}-darwin-{arch}.tar.gz"
checksum-file = "helm-v{version}-darwin-{arch}.tar.gz.sha256sum"
archive-prefix = "darwin-{arch}"
bin-path = "helm"

[platform.windows]
download-file = "helm-v{version}-windows-{arch}.zip"
checksum-file = "helm-v{version}-windows-{arch}.zip.sha256sum"
archive-prefix = "windows-{arch}"
bin-path = "helm.exe"

[install]
download-url = "https://get.helm.sh/{download_file}"
checksum-url = "https://get.helm.sh/{checksum_file}"
unpack = true

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/helm/helm"
