name = "kustomize"
type = "cli"

[platform.linux]
download-file = "kustomize_v{version}_linux_{arch}.tar.gz"
bin-path = "kustomize"

[platform.macos]
download-file = "kustomize_v{version}_darwin_{arch}.tar.gz"
bin-path = "kustomize"

[platform.windows]
download-file = "kustomize_v{version}_windows_{arch}.zip"
bin-path = "kustomize.exe"

[install]
download-url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{version}/{download_file}"
checksum-url = "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{version}/checksums.txt"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/kubernetes-sigs/kustomize"
git-tag-pattern = "^(?:kustomize/)(.*)$"
