name = "lefthook"
type = "cli"

[platform.linux]
download-file = "lefthook_{version}_Linux_{arch}.gz"
bin-path = "lefthook_{version}_Linux_{arch}"

[platform.macos]
download-file = "lefthook_{version}_MacOS_{arch}.gz"
bin-path = "lefthook_{version}_MacOS_{arch}"

[platform.windows]
download-file = "lefthook_{version}_Windows_{arch}.gz"
bin-path = "lefthook_{version}_Windows_{arch}.exe"

[install.arch]
aarch64 = "arm64"

[install]
download-url = "https://github.com/evilmartians/lefthook/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/evilmartians/lefthook/releases/download/v{version}/lefthook_checksums.txt"
unpack = false

[resolve]
git-url = "https://github.com/evilmartians/lefthook"
