name = "shellspec"
type = "cli"

[platform.linux]
download-file = "shellspec-dist.tar.gz"
archive-prefix = "shellspec-dist"
bin-path = "shellspec"

[platform.macos]
download-file = "shellspec-dist.tar.gz"
archive-prefix = "shellspec-dist"
bin-path = "shellspec"

[install]
download-url = "https://github.com/shellspec/shellspec/releases/download/{version}/{download_file}"

[resolve]
manifest-url = "https://api.github.com/repos/shellspec/shellspec/releases?per_page=100"
manifest-version-key = "tag_name"
version-pattern = "^v?(\\d+\\.\\d+\\.\\d+)$"
