name = "terraformer"
type = "cli"

[platform.linux]
download-file = "terraformer-all-linux-{arch}"
bin-path = "terraformer"

[platform.macos]
download-file = "terraformer-all-darwin-{arch}"
bin-path = "terraformer"

[install]
download-url = "https://github.com/GoogleCloudPlatform/terraformer/releases/download/{version}/{download_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
manifest-url = "https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases?per_page=100"
manifest-version-key = "tag_name"
version-pattern = "^v?(\\d+\\.\\d+\\.\\d+)$"
