name = "zizmor"
type = "cli"

[platform.linux]
download-file = "zizmor-{arch}-unknown-linux-gnu.tar.gz"

[platform.macos]
download-file = "zizmor-{arch}-apple-darwin.tar.gz"

[platform.windows]
download-file = "zizmor-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/zizmorcore/zizmor/releases/download/v{version}/{download_file}"

[resolve]
manifest-url = "https://api.github.com/repos/zizmorcore/zizmor/releases?per_page=100"
manifest-version-key = "tag_name"
version-pattern = "^v?(\\d+\\.\\d+\\.\\d+)$"
