# yaml-language-server: $schema=https://moonrepo.dev/schemas/project.json
language: typescript
tasks:
  run:
    command:
      - deno
      - run
      - --allow-read
      - main.ts
    options:
      shell: true
      cache: false
