# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
taskOptions:
  cache: false
  cacheLifetime: 3 hr
  shell: true
  unixShell: bash
  windowsShell: bash
  affectedFiles: true
tasks:
  fmt:
    inputs:
      - "**/*.ts"
    command:
      - deno
      - fmt
  lint:
    inputs:
      - "**/*.ts"
    command:
      - deno
      - lint
  test:
    inputs:
      - "**/*.ts"
    command:
      - deno
      - test
      - --allow-read
  ci:
    deps:
      - fmt
      - lint
      - test
    options:
      runDepsInParallel: false
      affectedFiles: false
      cache: false
inheritedBy:
  toolchain: deno
