# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
taskOptions:
  cache: false
  cacheLifetime: 3 hr
tasks:
  fmt:
    extends: _lintFormatBase
    inputs:
      - "**/*.ts"
    command:
      - deno
      - fmt
  lint:
    extends: _lintFormatBase
    inputs:
      - "**/*.ts"
    command:
      - deno
      - lint
  test:
    extends: _lintFormatBase
    inputs:
      - "**/*.ts"
    command:
      - deno
      - test
      - --allow-read
  ci:
    extends: _lintFormatBase
    deps:
      - fmt
      - lint
      - test
    options:
      runDepsInParallel: false
      affectedFiles: false
      cache: false
      internal: false
inheritedBy:
  toolchain: deno
