# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
taskOptions:
  cache: false
  cacheLifetime: 3 hr
tasks:
  fmt:
    extends: _lintFormatBase
    inputs:
      - "**/*.go"
    command:
      - dprint
      - fmt
      - --config $workspaceRoot/.dprint.json
      - "**/*.go"
  lint:
    extends: _lintFormatBase
    inputs:
      - "**/*.go"
    command:
      - dprint
      - check
      - --config $workspaceRoot/.dprint.json
      - "**/*.go"
  test:
    extends: _lintFormatBase
    inputs:
      - "**/*.go"
    command:
      - go
      - test
      - -overlay=$(go run github.com/tenntenn/testtime/cmd/testtime@v0.3.2)
  ci:
    extends: _lintFormatBase
    deps:
      - fmt
      - lint
      - test
    options:
      runDepsInParallel: false
      affectedFiles: false
      cache: false
      internal: false
inheritedBy:
  toolchain: go
