# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
taskOptions:
  cache: false
  cacheLifetime: 3 hr
  shell: true
  unixShell: bash
  windowsShell: bash
  affectedFiles: true
tasks:
  fmt:
    inputs:
      - "**/*.rs"
      - Cargo.toml
    command:
      - cargo
      - fmt
  lint:
    inputs:
      - "**/*.rs"
      - Cargo.toml
    command:
      - cargo
      - clippy
      - --
      - -D
      - warnings
  build:
    inputs:
      - "**/*.rs"
      - Cargo.toml
      - Cargo.lock
    command:
      - cargo
      - build
      - --release
  test:
    inputs:
      - "**/*.rs"
      - Cargo.toml
    command:
      - cargo
      - test
  ci:
    deps:
      - fmt
      - lint
      - test
    options:
      runDepsInParallel: false
      affectedFiles: false
      cache: false
inheritedBy:
  toolchain: rust
