name: "[CI] Proto Tools"

on:
    push:
        branches:
        - feature/**
        - hotfix/**
        paths:
        - '.github/workflows/ci.yaml'
        - 'src/**'
        - 'tests/**'
        - 'Cargo.toml'
    pull_request:
        branches:
        - develop
        - feature/**
        - hotfix/**
        paths:
        - '.github/workflows/ci.yaml'
        - 'src/**'
        - 'tests/**'
        - 'Cargo.toml'

jobs:
    run-test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2025, macos-15]
            fail-fast: false
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Toolchain
          uses: moonrepo/setup-toolchain@v0.5.0
          with:
            cache: false
            auto-install: true
