name: "[CI] Proto Tools"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  run-test:
    name: "${{ matrix.config.target }}"
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          # - os: macos-12
          # target: x86_64-apple-darwin
          - os: macos-15
            target: aarch64-apple-darwin
          - os: windows-2025
            target: x86_64-pc-windows-msvc
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@827700d97fe7dd1c3030018529e43e23c377c308 # v0.5.0
        with:
          cache: false
          auto-install: true

      - run: moon ci

      - run: ./.github/script/action
        if: success() || failure()
